/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormDetail_Pembelian.java
 *
 * Created on Jun 25, 2010, 9:59:09 PM
 */

package ClientApplication;
import ClientApplication.form.FormAdministrator;
import ClientApplication.form.FormApoteker;
import ClientApplication.form.FormBag_Pembayaran;
import ClientApplication.form.FormBag_Pendaftaran;
import ClientApplication.form.FormDokter;
import ClientApplication.form.FormKecantikan;
import ClientApplication.form.FormKepala_Klinik;
import ClientApplication.form.FormLab;
import ClientApplication.form.FormUSG;
import ClientApplication.form.FormBag_Pembayaran;
import Database.Service.AdministratorService;
import Database.Service.ApotekerService;
import Database.Service.Bag_PembayaranService;
import Database.Service.Bag_PendaftaranService;
import Database.Service.DokterService;
import Database.Service.KecantikanService;
import Database.Service.Kepala_KlinikService;
import Database.Service.LabService;
import Database.Service.USGService;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Tiara Ratna Sari
 */
public class FormLogin extends javax.swing.JFrame {
    
    public FormLogin(AdministratorService administratorService) throws RemoteException, NotBoundException{
        setSize(1024, 768);
        initComponents();
        setLocationRelativeTo(this);
    }
    
    public FormLogin() throws RemoteException, NotBoundException{
        initComponents();
        setLocationRelativeTo(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(usernameField);
        usernameField.setBounds(610, 355, 170, 30);
        getContentPane().add(passwordField);
        passwordField.setBounds(610, 402, 170, 30);

        loginButton.setBackground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Login");
        loginButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        getContentPane().add(loginButton);
        loginButton.setBounds(690, 450, 65, 28);

        clearButton.setBackground(new java.awt.Color(255, 255, 255));
        clearButton.setText("Clear");
        clearButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        getContentPane().add(clearButton);
        clearButton.setBounds(610, 450, 65, 28);

        exitButton.setBackground(new java.awt.Color(255, 255, 255));
        exitButton.setText("Exit");
        exitButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        getContentPane().add(exitButton);
        exitButton.setBounds(530, 450, 65, 28);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables

}
