/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Arlin
 *
 * 
 */

package ClientApplication.form;

import ClientApplication.FormLogin;
import ClientApplication.model.TableModelUSG;
import Database.Entity.USG;
import Database.Service.USGService;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;


/**
 *
 * @author Arlin
 */
public class FormUSG extends javax.swing.JFrame {
private TableModelUSG tableModelusg = new TableModelUSG();
    private USGService usgService;
    
    public FormUSG(USGService usgService) {
        this.usgService = usgService;
        try{
            tableModelusg.setData(this.usgService.getUSG());
        }catch(RemoteException exception){
            exception.printStackTrace();
        }
        initComponents();
        setLocationRelativeTo(this);
        setSize(665, 730);

        jTable1.setModel(tableModelusg);
        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            public void valueChanged(ListSelectionEvent e) {
                int row = jTable1.getSelectedRow();
                if(row != -1){
                    USG usg = tableModelusg.get(row);
                    jTextField1.setText(usg.getId_pasien());
                    jTextField4.setText(usg.getId_USG());
//                    jTextField6.setset(usg.getHasil());
                    jTextArea1.setText(usg.getDeskripsi());
                    jTextField7.setText(String.valueOf(usg.getHarga()));
                }
            }
        });
    }
    
    public void clear(){
        jTextField1.setText("");
        jTextField4.setText("");
        jTextField6.setText("");
        jTextArea1.setText("");
        jTextField7.setText("");
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setText("ID Pasien              :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(150, 200, 100, 14);

        jLabel3.setText("Nama Pasien         :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(150, 230, 100, 14);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(250, 200, 80, 20);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(250, 230, 180, 20);

        jLabel4.setText("Tanggal Pemerikasaan :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(530, 170, 130, 14);

        jLabel5.setText("ID USG          :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(530, 200, 70, 14);

        jLabel6.setText("ID Petugas    :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(530, 230, 90, 14);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(660, 170, 80, 20);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(660, 200, 80, 20);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(660, 230, 80, 20);

        jLabel7.setText("Hasil pemeriksaan :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(150, 270, 100, 14);
        jPanel1.add(jTextField6);
        jTextField6.setBounds(250, 270, 260, 20);

        jButton1.setText("Unggah");
        jPanel1.add(jButton1);
        jButton1.setBounds(530, 270, 69, 23);

        jLabel8.setText("Keterangan          :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(150, 300, 100, 14);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(250, 300, 260, 150);

        jLabel9.setText("Fasilitas               :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(150, 460, 100, 14);

        jRadioButton1.setText("Foto USG");
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(250, 460, 71, 23);

        jRadioButton2.setText("CD usg");
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(450, 460, 59, 23);

        jRadioButton3.setText("Vitamin/Suplemen");
        jPanel1.add(jRadioButton3);
        jRadioButton3.setBounds(250, 490, 120, 23);

        jLabel10.setText("Detail transaksi   :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(150, 520, 90, 14);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Fasilitas", "Biaya"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(250, 520, 270, 100);

        jLabel11.setText("Total transasksi :");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(150, 630, 90, 14);
        jPanel1.add(jTextField7);
        jTextField7.setBounds(250, 630, 140, 20);

        jButton2.setText("Simpan");
        jPanel1.add(jButton2);
        jButton2.setBounds(540, 650, 67, 23);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/6.jpg"))); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(0, 0, 1300, 770);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1268, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables

}
