/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormPembelian.java
 *
 * Created on Jun 25, 2010, 9:45:09 PM
 */

package ClientApplication.form;

import com.mysql.jdbc.Statement;
import ClientApplication.FormLogin;
import ClientApplication.model.TableModelLab_detailLab;
import Database.Entity.Lab_detailLab;
import Database.Service.LabService;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;




/**
 *
 * @author Tiara Ratna Sari
 */
public class FormLab extends javax.swing.JFrame {
    
    
private TableModelLab_detailLab tableModellab = new TableModelLab_detailLab();
    private LabService labService;
    
    public FormLab(LabService labService) {
        this.labService = labService;
        try{
            tableModellab.setData(this.labService.getLab_detailLab());
        }catch(RemoteException exception){
            exception.printStackTrace();
        }
        initComponents();
        setLocationRelativeTo(this);
        setSize(665, 730);
//
//        jTable1.setModel(tableModellab);
//        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
//
//            public void valueChanged(ListSelectionEvent e) {
//                int row = jTable1.getSelectedRow();
//                if(row != -1){
//                    Lab_detailLab lab = tableModellab.get(row);
//                    idpasien.setText(lab.getId_Pasien());
//                    //namapasien.setText(lab.get());
//                    idLab.setText(lab.getId_Lab());
////                    TextField_Lab.setText(String.valueOf(pembayaran.getId_Detail_Lab()));
////                    TextField_Resep.setText(String.valueOf(pembayaran.getId_Resep()));
////                    TextField_Resep.setText(String.valueOf(pembayaran.getId_Rekam()));
////                    TextField_Kecantikan.setText(String.valueOf(pembayaran.getId_Transaksi_Layanan()));
//                    totalTransaksi.setText(String.valueOf(lab.getTotal_Harga()));
////                    TextField_status.setText(String.valueOf(pembayaran.getStatus()));
//                }
//            }
//        });
//    }
//    
//    
//    public void clear(){
//        idpasien.setText("");
//        idLab.setText("");
//        totalTransaksi.setText("");
//        TextField_tglPembayaran.setText("");
//        TextField_Kecantikan.setText("");
//        TextField_Lab.setText("");
//        TextField_RekamMedis.setText("");
//        TextField_Resep.setText("");
//        TextField_Usg.setText("");
//        TextField_totalPembayaran.setText("");
//        TextField_status.setText("");
    }
    




    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idpasien = new javax.swing.JTextField();
        namaPasien = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tanggal = new javax.swing.JTextField();
        idLab = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        hasilPemeriksaan = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Keterangan = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        totalTransaksi = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        tesDarah = new javax.swing.JTextField();
        tesHIV = new javax.swing.JTextField();
        tesUrine = new javax.swing.JTextField();
        tesKimia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("ID Pasien                       :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 320, 153, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nama Pasien                  :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(190, 350, 160, 17);

        idpasien.setEditable(false);
        getContentPane().add(idpasien);
        idpasien.setBounds(350, 320, 212, 20);

        namaPasien.setEditable(false);
        namaPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaPasienActionPerformed(evt);
            }
        });
        getContentPane().add(namaPasien);
        namaPasien.setBounds(350, 350, 212, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Tanggal Pemeriksaan      : ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(730, 240, 161, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("ID LAB                            :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(730, 270, 158, 17);

        tanggal.setEditable(false);
        getContentPane().add(tanggal);
        tanggal.setBounds(890, 240, 220, 20);

        idLab.setEditable(false);
        getContentPane().add(idLab);
        idLab.setBounds(890, 270, 220, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Jenis Pemeriksaan           : ");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(190, 410, 162, 17);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Hasil Pemeriksaan           :");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(730, 350, 155, 17);

        jCheckBox1.setText("Tes Darah");
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(350, 410, 80, 23);

        jCheckBox2.setText("Tes HIV");
        getContentPane().add(jCheckBox2);
        jCheckBox2.setBounds(350, 450, 80, 23);

        jCheckBox3.setText("Tes Kimia");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox3);
        jCheckBox3.setBounds(350, 540, 80, 23);

        jCheckBox4.setText("Tes Urine");
        getContentPane().add(jCheckBox4);
        jCheckBox4.setBounds(350, 490, 80, 23);
        getContentPane().add(hasilPemeriksaan);
        hasilPemeriksaan.setBounds(890, 350, 220, 20);

        jButton1.setText("Browser");
        getContentPane().add(jButton1);
        jButton1.setBounds(1120, 350, 71, 23);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Keterangan                    :");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(730, 390, 168, 17);

        Keterangan.setColumns(20);
        Keterangan.setRows(5);
        jScrollPane2.setViewportView(Keterangan);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(890, 390, 220, 96);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Total Tansaksi                 :");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(2689, 1501, 158, 17);

        jTextField11.setEditable(false);
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField11);
        jTextField11.setBounds(2851, 1501, 222, 20);

        jButton2.setText("Simpan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(3083, 1539, 67, 23);
        getContentPane().add(jLabel16);
        jLabel16.setBounds(483, 187, 0, 0);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Total Transaksi               :");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(720, 560, 160, 17);

        totalTransaksi.setEditable(false);
        getContentPane().add(totalTransaksi);
        totalTransaksi.setBounds(890, 560, 270, 20);

        jButton3.setText("Simpan ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(1090, 600, 69, 23);
        getContentPane().add(tesDarah);
        tesDarah.setBounds(450, 410, 150, 20);
        getContentPane().add(tesHIV);
        tesHIV.setBounds(450, 450, 150, 20);
        getContentPane().add(tesUrine);
        tesUrine.setBounds(450, 490, 150, 20);
        getContentPane().add(tesKimia);
        tesKimia.setBounds(450, 540, 150, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/7.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1230, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namaPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaPasienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaPasienActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Keterangan;
    private javax.swing.JTextField hasilPemeriksaan;
    private javax.swing.JTextField idLab;
    private javax.swing.JTextField idpasien;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField namaPasien;
    private javax.swing.JTextField tanggal;
    private javax.swing.JTextField tesDarah;
    private javax.swing.JTextField tesHIV;
    private javax.swing.JTextField tesKimia;
    private javax.swing.JTextField tesUrine;
    private javax.swing.JTextField totalTransaksi;
    // End of variables declaration//GEN-END:variables

}
