/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormSuplier.java
 *
 * Created on Jun 25, 2010, 9:35:19 PM
 */

package ClientApplication.form;

import ClientApplication.FormLogin;
import ClientApplication.model.TableModelLaporanJumlahPasien;
import ClientApplication.model.TableModelLaporanKeuangan;
import ClientApplication.model.TableModelPembayaran;
import Database.Entity.Pembayaran;
import ClientApplication.model.TableModelPasien;
import Database.Entity.Pasien;
import ClientApplication.model.TableModelObat_detailResep;
import Database.Entity.Obat_detailResep;
import Database.Service.Kepala_KlinikService;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author Tiara Ratna Sari
 */
public class FormKepala_Klinik extends javax.swing.JFrame {
    Kepala_KlinikService kepala_KlinikService;
    TableModelLaporanKeuangan tableModelLaporanKeuangan  = new TableModelLaporanKeuangan();
    TableModelLaporanJumlahPasien tableModelLaporanJumlahPasien = new TableModelLaporanJumlahPasien();

    public FormKepala_Klinik(Kepala_KlinikService kepala_KlinikService) {
        this.kepala_KlinikService = kepala_KlinikService;
        try{
            tableModelLaporanKeuangan.setData(this.kepala_KlinikService.getLaporanKeuangan());
            tableModelLaporanJumlahPasien.setData(this.kepala_KlinikService.getLaporanJumlahPasien());
        }catch(RemoteException exception){
            exception.printStackTrace();
        }
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("Pembayaran");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(100, 340, 130, 40);

        jButton2.setText("Jumlah Pasien");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(440, 340, 130, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/9.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1318, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JasperPrint jasperPrint = null;
        try {
            JasperCompileManager.compileReportToFile("src/Report/laporanKeuangan.jrxml");
            HashMap hash = new HashMap();
            //            hash.put("ID_PEMBAYARAN",FieldLk_idPembayaran.getText());
            //            System.out.println(FieldLk_idPembayaran.getText());
            jasperPrint = JasperFillManager.fillReport("src/Report/laporanKeuangan.jasper", hash,
                new JRTableModelDataSource(tableModelLaporanKeuangan));
            JasperViewer jasperViewer = new JasperViewer(jasperPrint);
            jasperViewer.setVisible(true);
        } catch (JRException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JasperPrint jasperPrint = null;
        try {
            JasperCompileManager.compileReportToFile("src/Report/jumlahpasien.jrxml");
            HashMap hash = new HashMap();
            //            hash.put("ID_PEMBAYARAN",FieldLk_idPembayaran.getText());
            //            System.out.println(FieldLk_idPembayaran.getText());
            jasperPrint = JasperFillManager.fillReport("src/Report/jumlahpasien.jasper", hash,
                new JRTableModelDataSource(tableModelLaporanJumlahPasien));
            JasperViewer jasperViewer = new JasperViewer(jasperPrint);
            jasperViewer.setVisible(true);
        } catch (JRException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
